spring.application.name=music-module
spring.config.import=nacos:music-module.properties?group=DEFAULT_GROUP
spring.cloud.nacos.discovery.server-addr=${NACOS_ADDR:127.0.0.1:8848}
spring.cloud.nacos.discovery.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.discovery.password=${NACOS_PASSWORD:nacos}
spring.cloud.nacos.discovery.namespace=${NACOS_NAMESPACE:local}
spring.cloud.nacos.discovery.group=DEFAULT_GROUP
spring.cloud.nacos.config.server-addr=${NACOS_ADDR:127.0.0.1:8848}
spring.cloud.nacos.config.username=${NACOS_USERNAME:nacos}
spring.cloud.nacos.config.password=${NACOS_PASSWORD:nacos}
spring.cloud.nacos.config.namespace=${NACOS_NAMESPACE:local}
spring.cloud.nacos.config.group=DEFAULT_GROUP
spring.cloud.nacos.config.file-extension=properties

