<script setup>
import { onBeforeUnmount,onMounted,ref } from 'vue'
import { ElMessage } from 'element-plus'
import { appApi } from '../../api/app'
import { useRoute,useRouter } from 'vue-router'
const route=useRoute(),router=useRouter(),mode=ref('login'),loading=ref(false),phase=ref(0),form=ref({phone:'',password:'',name:'',gender:1}),user=ref(JSON.parse(localStorage.getItem('musiccard_user')||'null'))
let timer
const waveHeight=n=>`${28+Math.round((Math.sin(phase.value*.46+n*.82)+1)*29)+((n*17)%18)}%`
onMounted(()=>{timer=window.setInterval(()=>phase.value++,120)})
onBeforeUnmount(()=>window.clearInterval(timer))
async function submit(){if(!/^1\d{10}$/.test(form.value.phone))return ElMessage.warning('请输入正确的 11 位手机号码');if(!form.value.password)return ElMessage.warning('请输入密码');if(mode.value==='register'&&!form.value.name)return ElMessage.warning('请输入昵称');loading.value=true;try{const {result}=mode.value==='login'?await appApi.login(form.value):await appApi.register(form.value);localStorage.setItem('musiccard_sign',result.sign);localStorage.setItem('musiccard_user',JSON.stringify(result.userInfo));user.value=result.userInfo;ElMessage.success('欢迎进入 MusicCard');const redirect=route.query.redirect;router.replace(typeof redirect==='string'&&redirect.startsWith('/app/')?redirect:'/app/explore')}catch(error){ElMessage.error(error?.message||'登录请求失败，请确认 user 服务已启动（8083）')}finally{loading.value=false}}
function logout(){localStorage.removeItem('musiccard_sign');localStorage.removeItem('musiccard_user');user.value=null}
</script>
<template><div class="account"><section class="pitch"><span class="eyebrow">YOUR PRIVATE FREQUENCY</span><h1>保存你与声音<br>相遇的每个瞬间。</h1><div class="waves"><i v-for="n in 32" :key="n" :style="{height:waveHeight(n)}"></i></div><p class="signal">● LIVE FREQUENCY · {{String(phase%100).padStart(2,'0')}}.{{String((phase*7)%100).padStart(2,'0')}} HZ</p></section><section class="panel glass"><template v-if="user"><span class="avatar">{{user.name?.slice(0,2)}}</span><h2>{{user.name}}</h2><p>{{user.phone}}</p><div class="account-stat"><span><b>24</b>收藏</span><span><b>08</b>声场</span></div><el-button @click="logout">退出登录</el-button></template><template v-else><div class="tabs"><button :class="{active:mode==='login'}" @click="mode='login'">登录</button><button :class="{active:mode==='register'}" @click="mode='register'">注册</button></div><h2>{{mode==='login'?'回到你的声场':'创建你的声音坐标'}}</h2><el-form label-position="top" @submit.prevent="submit"><el-form-item v-if="mode==='register'" label="昵称"><el-input v-model="form.name" placeholder="如何称呼你"/></el-form-item><el-form-item label="手机号码"><el-input v-model="form.phone" placeholder="11 位手机号码"/></el-form-item><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password/></el-form-item><el-form-item v-if="mode==='register'" label="性别"><el-radio-group v-model="form.gender"><el-radio :value="1">男</el-radio><el-radio :value="2">女</el-radio></el-radio-group></el-form-item><el-button type="primary" native-type="submit" :loading="loading">{{mode==='login'?'进入 MusicCard':'完成注册'}}</el-button></el-form></template></section></div></template>
<style scoped>.account{min-height:calc(100vh - 76px);display:grid;grid-template-columns:1.1fr .9fr;align-items:center;gap:8vw;padding:60px clamp(20px,10vw,160px);background:linear-gradient(110deg,var(--ink-950) 0 52%,transparent 52%);color:#fff}.pitch h1{font:clamp(52px,7vw,92px)/.88 var(--display);letter-spacing:-.06em;margin:20px 0}.waves{height:116px;display:flex;align-items:center;gap:5px;max-width:520px}.waves i{width:4px;background:linear-gradient(var(--cyan),var(--violet));border-radius:5px;transition:height .1s linear}.signal{margin-top:15px;font:10px var(--mono);letter-spacing:.14em;color:#7e93ae}.panel{padding:38px;color:var(--ink-950);border-radius:28px;max-width:470px;width:100%}.tabs{display:flex;gap:22px}.tabs button{border:0;background:none;padding:8px 0;color:var(--muted);font-weight:700}.tabs .active{color:var(--ink-950);border-bottom:2px solid var(--violet)}.panel h2{font:34px var(--display);margin:25px 0}.panel :deep(.el-button--primary){width:100%}.avatar{width:76px;height:76px;display:grid;place-items:center;border-radius:24px;background:var(--ink-950);color:var(--cyan);font:20px var(--mono)}.account-stat{display:flex;gap:40px;margin:30px 0}.account-stat span{display:grid;color:var(--muted);font-size:11px}.account-stat b{font:32px var(--display);color:var(--ink-950)}@media(max-width:780px){.account{grid-template-columns:1fr;background:linear-gradient(var(--ink-950) 0 45%,var(--paper) 45%);padding:55px 20px}.pitch h1{font-size:50px}.waves{height:70px}.panel{justify-self:center}}</style>
