<script setup>
import { computed,onBeforeUnmount,onMounted,ref } from 'vue'
import { Search } from '@element-plus/icons-vue'
import AlbumArtwork from '../../components/AlbumArtwork.vue'
import MusicMasonry from '../../components/MusicMasonry.vue'
import { appApi } from '../../api/app'
const keyword=ref(''),applied=ref(''),items=ref([]),loading=ref(false),wp=ref(''),isEnd=ref(false),requested=ref(new Set())
const headline=computed(()=>applied.value?`“${applied.value}” 的声场`:'今天，听点不一样的')
async function load(reset=false){if(loading.value||(!reset&&isEnd.value))return;if(reset){items.value=[];wp.value='';isEnd.value=false;requested.value=new Set()}const cursor=wp.value||'first';if(requested.value.has(cursor))return;requested.value.add(cursor);loading.value=true;try{const params=wp.value?{wp:wp.value}:(applied.value?{keyword:applied.value}:{});const {result}=await appApi.musicList(params);const fresh=(result.list||[]).filter(item=>!items.value.some(old=>old.id===item.id));items.value.push(...fresh);wp.value=result.wp||'';isEnd.value=Boolean(result.isEnd)||!fresh.length}catch(error){requested.value.delete(cursor);throw error}finally{loading.value=false}}
function search(){applied.value=keyword.value.trim();load(true)}
function maybeLoadNext(){if(window.scrollY+window.innerHeight>=document.documentElement.scrollHeight-620)load()}
onMounted(async()=>{await load(true);window.addEventListener('scroll',maybeLoadNext,{passive:true})})
onBeforeUnmount(()=>window.removeEventListener('scroll',maybeLoadNext))
</script>
<template><div class="explore"><section class="hero"><div class="hero-copy"><span class="eyebrow">DISCOVERY FEED · {{new Date().toLocaleDateString('zh-CN')}}</span><h1>声音不是背景，<br><i>是你此刻的坐标。</i></h1><p>从独立制作到电子脉冲，用一张张音乐卡片，找到与你同频的声音。</p><div class="search glass"><el-input v-model="keyword" size="large" placeholder="搜索歌曲、歌手或一种情绪" clearable @keyup.enter="search"><template #prefix><el-icon><Search/></el-icon></template></el-input><el-button type="primary" size="large" @click="search">开始探索</el-button></div><div class="quick"><span>试试：</span><button v-for="k in ['夜行','电子','治愈']" :key="k" @click="keyword=k;search()">{{k}}</button></div></div><div class="hero-visual"><div class="halo"></div><AlbumArtwork :item="{id:88,musicName:'无垠频率',ar:1,palette:['#09182b','#30d9ff','#7c6cff']}"/><div class="now glass"><i></i><span><small>NOW SIGNALING</small><b>无垠频率 · MusicCard Select</b></span></div></div></section><section class="feed"><div class="section-head"><div><span class="eyebrow">CURATED STREAM</span><h2>{{headline}}</h2><p>{{items.length}} 张卡片正在你的轨道上</p></div><span class="feed-state">{{isEnd?'已抵达声场边界':'持续探索中'}} <i></i></span></div><div v-loading="loading"><MusicMasonry :items="items"/></div><div class="load-more"><span v-if="loading">正在接入下一段声场…</span><span v-else-if="isEnd">— END OF FREQUENCY —</span><span v-else>继续向下滚动，自动接入更多卡片</span></div></section></div></template>
<style scoped>.explore{overflow:hidden}.hero{min-height:650px;padding:80px clamp(20px,7vw,108px);display:grid;grid-template-columns:1.08fr .92fr;align-items:center;gap:7vw}.hero-copy h1{margin:18px 0 22px;font-family:var(--display);font-size:clamp(48px,7vw,96px);line-height:.87;letter-spacing:-.065em}.hero-copy h1 i{font-style:normal;color:transparent;-webkit-text-stroke:1.5px var(--ink-950)}.hero-copy>p{max-width:570px;color:var(--muted);font-size:16px;line-height:1.8}.search{display:flex;gap:10px;max-width:620px;margin-top:34px;padding:10px;border-radius:18px}.search :deep(.el-input__wrapper){box-shadow:none!important;background:transparent}.quick{display:flex;align-items:center;gap:8px;margin-top:13px;color:var(--muted);font-size:12px}.quick button{border:0;background:transparent;color:var(--violet);cursor:pointer}.hero-visual{position:relative;max-width:510px;justify-self:end;width:100%;transform:rotate(2deg)}.hero-visual :deep(.art){min-height:460px;border-radius:32px;box-shadow:0 45px 90px rgba(7,17,31,.28)}.halo{position:absolute;width:80%;aspect-ratio:1;border-radius:50%;right:-18%;top:-20%;background:var(--cyan);filter:blur(95px);opacity:.22}.now{position:absolute;left:-50px;right:40px;bottom:-25px;display:flex;align-items:center;gap:13px;padding:16px 18px;border-radius:16px;transform:rotate(-2deg)}.now>i{width:10px;height:10px;border-radius:50%;background:var(--coral);box-shadow:0 0 12px var(--coral)}.now span{display:grid}.now small{font:8px var(--mono);letter-spacing:.15em;color:var(--muted)}.now b{font-size:12px}.feed{padding:70px clamp(20px,5vw,72px)}.feed-state{font:11px var(--mono);color:var(--muted)}.feed-state i{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--lime);box-shadow:0 0 8px var(--lime)}.load-more{text-align:center;padding:38px;color:var(--muted);font:10px var(--mono);letter-spacing:.14em}@media(max-width:780px){.hero{padding-top:54px;grid-template-columns:1fr}.hero-visual{max-width:460px;justify-self:center;margin-top:38px}.section-head{align-items:start}.feed-state{display:none}}@media(max-width:520px){.hero{padding:42px 18px 60px}.hero-copy h1{font-size:52px}.search{display:grid}.hero-visual :deep(.art){min-height:320px}.now{left:12px;right:12px}.feed{padding:50px 14px}}</style>
