spring.profiles.include=local,druid

spring.application.name=app

server.port=8080

server.tomcat.threads.max=200
server.tomcat.threads.min-spare=10
server.tomcat.max-connections=8192
server.tomcat.accept-count=100
server.tomcat.connection-timeout=20000

spring.jackson.default-property-inclusion=non_absent

oss.bucket=musiccard-resources
oss.region=cn-wuhan-lr
oss.endpoint=https://oss-cn-wuhan-lr.aliyuncs.com
oss.host=https://musiccard-resources.oss-cn-wuhan-lr.aliyuncs.com
oss.dir=uploads

mybatis.config-location=classpath:mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:mybatis/mapper/**/*.xml
mybatis-plus.type-handlers-package=com.beat.mall.module.file.handler

application.isapp=1
application.pagesize=10
application.sign.key=sign
application.session.key=_USER
