<script setup>
import { computed, ref, watch } from 'vue'
const props=defineProps({item:{type:Object,default:()=>({})},height:{type:String,default:'auto'}})
const palette=props.item.palette||['#132b4d','#30d9ff','#7c6cff']
const imageUrl=computed(()=>{const item=props.item||{};const covers=item.coverImages;return item.wallImage?.url||item.coverUrl||item.imageUrl||(Array.isArray(covers)?covers[0]:covers)||item.typeImage||''})
const imageFailed=ref(false)
watch(imageUrl,()=>{imageFailed.value=false})
</script>
<template><div class="art" :style="{'--c0':palette[0],'--c1':palette[1],'--c2':palette[2],aspectRatio:item.ar||item.wallImage?.ar||1,height}"><img v-if="imageUrl&&!imageFailed" class="db-cover" :src="imageUrl" alt="" @error="imageFailed=true"><template v-else><span class="orbit one"></span><span class="orbit two"></span><span class="record"><i></i></span><div class="copy"><small>MC—{{ String(item.id||1).padStart(3,'0') }}</small><strong>{{ item.musicName||item.typeName }}</strong></div><div class="bars"><i v-for="n in 11" :key="n" :style="{height:(18+((n*13+(item.id||1)*7)%44))+'%'}"></i></div></template></div></template>
<style scoped>.art{position:relative;min-height:170px;overflow:hidden;border-radius:18px;background:radial-gradient(circle at 75% 18%,color-mix(in srgb,var(--c1) 54%,transparent),transparent 32%),linear-gradient(145deg,var(--c0),color-mix(in srgb,var(--c0) 70%,var(--c2)));color:#fff;isolation:isolate}.art:after{content:"";position:absolute;inset:0;background-image:linear-gradient(rgba(255,255,255,.07) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.07) 1px,transparent 1px);background-size:24px 24px;mask-image:linear-gradient(to bottom,black,transparent)}.db-cover{width:100%;height:100%;min-height:inherit;display:block;object-fit:cover;position:absolute;inset:0;z-index:4}.orbit{position:absolute;border:1px solid color-mix(in srgb,var(--c1) 72%,white);border-radius:50%;opacity:.7}.one{width:78%;aspect-ratio:1;right:-34%;top:-44%;box-shadow:0 0 50px color-mix(in srgb,var(--c1) 38%,transparent)}.two{width:48%;aspect-ratio:1;right:-5%;bottom:-30%}.record{position:absolute;width:38%;aspect-ratio:1;border-radius:50%;right:10%;top:19%;background:repeating-radial-gradient(circle,rgba(5,13,25,.96) 0 2px,rgba(255,255,255,.12) 3px 4px);display:grid;place-items:center;box-shadow:14px 20px 30px rgba(0,0,0,.25);z-index:2}.record i{width:19%;aspect-ratio:1;border-radius:50%;background:var(--c1);box-shadow:0 0 16px var(--c1)}.copy{position:absolute;left:16px;top:15px;max-width:58%;z-index:3}.copy small{display:block;font:9px var(--mono);letter-spacing:.15em;opacity:.72}.copy strong{display:block;margin-top:6px;font-family:var(--display);font-size:clamp(20px,3vw,34px);line-height:.88;letter-spacing:-.05em}.bars{position:absolute;display:flex;align-items:end;gap:3px;left:17px;right:48%;bottom:17px;height:34px;z-index:3}.bars i{flex:1;background:var(--c1);border-radius:2px 2px 0 0;opacity:.86}</style>
