<script setup>
import { computed } from 'vue'
import AlbumArtwork from './AlbumArtwork.vue'
const props=defineProps({items:{type:Array,default:()=>[]}})
const bricks=[{height:312,label:'NIGHT / 01'},{height:206,label:'PULSE / 02'},{height:376,label:'ECHO / 03'},{height:248,label:'FLOW / 04'},{height:338,label:'WAVE / 05'}]
const columns=computed(()=>{const out=bricks.map((brick,index)=>({brick,index,items:[],weight:brick.height}));props.items.forEach((item,index)=>{const target=out.reduce((a,b)=>a.weight<=b.weight?a:b);const ratio=[.82,1.2,.94,1.34,1.05][(item.id||index)%5];target.items.push({...item,_ratio:ratio,_index:index});target.weight+=230/ratio+118});return out})
</script>
<template><div class="masonry-feed"><section v-for="column in columns" :key="column.index" class="masonry-column"><div class="starter-brick" :style="{height:column.brick.height+'px'}"><span>{{column.brick.label}}</span><i></i><b></b></div><router-link v-for="item in column.items" :key="item.id" :to="`/app/music/${item.id}`" class="music-card"><AlbumArtwork :item="{...item,ar:item._ratio}"/><div class="meta"><div><h3>{{item.musicName}}</h3><p>{{item.singerName}} · {{item.typeName}}</p></div><button aria-label="查看详情">↗</button></div><p class="desc">{{item.musicDesc}}</p><div class="card-foot"><span>0{{(item._index%9)+1}} / SIGNAL</span><i></i></div></router-link></section></div></template>
<style scoped>.masonry-feed{--masonry-gap:24px;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));column-gap:var(--masonry-gap);align-items:start}.masonry-column{display:grid;grid-auto-flow:row;row-gap:var(--masonry-gap);align-content:start;min-width:0}.masonry-column>*{box-sizing:border-box;margin:0;min-width:0}.starter-brick{position:relative;overflow:hidden;border:1px solid rgba(48,217,255,.16);border-radius:22px;background:linear-gradient(145deg,#071527,#193b62);box-shadow:0 8px 18px rgba(20,43,67,.08);color:#dff9ff}.starter-brick:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,rgba(48,217,255,.13) 0 1px,transparent 1px 32px),repeating-linear-gradient(rgba(48,217,255,.1) 0 1px,transparent 1px 32px);mask-image:linear-gradient(to bottom,black,transparent)}.starter-brick span{position:absolute;left:15px;top:15px;font:9px var(--mono);letter-spacing:.14em}.starter-brick i,.starter-brick b{position:absolute;border-radius:50%;border:1px solid rgba(48,217,255,.5);animation:orbit 6s linear infinite}.starter-brick i{width:120px;aspect-ratio:1;right:-40px;bottom:-42px}.starter-brick b{width:56px;aspect-ratio:1;right:30px;bottom:35px;border-color:rgba(124,108,255,.8);animation-direction:reverse;animation-duration:4s}.music-card{display:block;padding:11px;background:#fff;border:1px solid var(--line);border-radius:22px;box-shadow:0 7px 16px rgba(20,43,67,.06);transition:transform .25s,box-shadow .25s}.music-card:hover{transform:translateY(-3px);box-shadow:0 14px 26px rgba(20,43,67,.13)}.meta{display:flex;justify-content:space-between;align-items:start;padding:13px 5px 4px}.meta h3{margin:0 0 4px;font-size:16px}.meta p,.desc{margin:0;color:var(--muted);font-size:11px}.meta button{width:32px;height:32px;border:1px solid var(--line);border-radius:50%;background:#fff}.desc{padding:8px 5px 13px;line-height:1.65}.card-foot{display:flex;align-items:center;gap:10px;padding:8px 5px 3px;border-top:1px solid var(--line);font:8px var(--mono);letter-spacing:.12em;color:#9aa8b8}.card-foot i{height:1px;flex:1;background:linear-gradient(90deg,var(--cyan),transparent)}@keyframes orbit{to{transform:rotate(360deg)}}@media(max-width:1100px){.masonry-feed{grid-template-columns:repeat(4,minmax(0,1fr))}.masonry-column:nth-child(5){display:none}}@media(max-width:780px){.masonry-feed{--masonry-gap:12px;grid-template-columns:repeat(2,minmax(0,1fr))}.masonry-column:nth-child(n+3){display:none}.starter-brick{height:150px!important;border-radius:15px}.music-card{padding:8px;border-radius:16px}.desc{display:none}.meta h3{font-size:14px}.meta button{display:none}}</style>
