spring.application.name=console
server.port=8081

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/musiccard
spring.datasource.username=root
spring.datasource.password=123456

spring.jackson.default-property-inclusion=non_null

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImp

oss.bucket=musiccard-resources
oss.region=cn-wuhan-lr
oss.endpoint=https://oss-cn-wuhan-lr.aliyuncs.com
oss.host=https://musiccard-resources.oss-cn-wuhan-lr.aliyuncs.com
oss.dir=uploads

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=100MB

mybatis-plus.type-handlers-package=top.yuhanpeng.musiccard.module.handler